const QUERY_KEY = {
  USER: {
    GET_USER_BY_ID: 'GET_USER_BY_ID',
  },
  DEPARMENT: {
    GET_LIST_DEPARTMENT: 'GET_LIST_DEPARTMENT',
    GET_DEPARTMENT_BY_ID: 'GET_DEPARTMENT_BY_ID',
  },
  DOCTOR: {
    GET_LIST_DOCTOR: 'GET_LIST_DOCTOR',
  },
  ARTICLE: {
    GET_ARTICLE_BY_ID: 'GET_ARTICLE_BY_ID',
    GET_ARTICLE_BY_SLUG: 'GET_ARTICLE_BY_SLUG',
    GET_RELATED_ARTICLES: 'GET_RELATED_ARTICLES',
    SEARCH_ARTICLES: 'SEARCH_ARTICLES',
    GET_ARTICLES_BY_CATEGORY: 'GET_ARTICLES_BY_CATEGORY',
    GET_FEATURED_ARTICLES: 'GET_FEATURED_ARTICLES',
    GET_FEATURED_ARTICLES_BY_CATEGORY: 'GET_FEATURED_ARTICLES_BY_CATEGORY',
  },
  CATEGORY: {
    GET_CATEGORIES: 'GET_CATEGORIES',
  },
  CONTACT: {
    SEND_CONTACT: 'SEND_CONTACT',
    GET_CONTACTS: 'GET_CONTACTS',
    GET_MY_CONTACTS: 'GET_MY_CONTACTS',
  },
  MEDICAL_SERVICE: {
    GET_LIST_MEDICAL_SERVICE: 'GET_LIST_MEDICAL_SERVICE',
  },
  PATIENT: {
    GET_PATIENT_INFORMATION: 'GET_PATIENT_INFORMATION',
    GET_PATIENTS: 'GET_PATIENTS',
  },
  INVOICE: {
    GET_LIST_INVOICE: 'GET_LIST_INVOICE',
    GET_INVOICE_BY_ID: 'GET_INVOICE_BY_ID',
    GET_UNBILLED_ITEMS: 'GET_UNBILLED_ITEMS',
  },
  INSURANCE: {
    GET_INSURANCES_BY_USER: 'GET_INSURANCES_BY_USER',
  },
  PAYMENT: {
    GET_PAYMENT_BY_ID: 'GET_PAYMENT_BY_ID',
    GET_PAYMENT_BY_INVOICE_ID: 'GET_PAYMENT_BY_INVOICE_ID',
  },
  STATISTICS: {
    ADMIN_SUMMARY: 'ADMIN_DASHBOARD_SUMMARY',
    STAFF_BY_DEPARTMENT: 'STAFF_BY_DEPARTMENT',
    REVENUE_BY_DAY: 'REVENUE_BY_DAY',
    APPOINTMENTS_BY_DAY: 'APPOINTMENTS_BY_DAY',
    // Doctor Dashboard
    DOCTOR_SUMMARY: 'DOCTOR_DASHBOARD_SUMMARY',
    DOCTOR_APPOINTMENTS_BY_DAY: 'DOCTOR_APPOINTMENTS_BY_DAY',
    DOCTOR_APPOINTMENT_STATUS: 'DOCTOR_APPOINTMENT_STATUS',
  },
  APPOINTMENT: {
    GET_AVAILABLE_SLOTS: 'GET_AVAILABLE_SLOTS',
    GET_APPOINTMNETS: 'GET_APPOINTMNETS',
  },
  MEDICAL_RESULT: {
    GET_BY_ID: 'GET_MEDICAL_RESULT_BY_ID',
    GET_BY_PATIENT: 'GET_MEDICAL_RESULTS_BY_PATIENT',
    GET_BY_DOCTOR: 'GET_MEDICAL_RESULTS_BY_DOCTOR',
    GET_BY_ADMIN: 'GET_MEDICAL_RESULTS_BY_ADMIN',
  },
  NOTIFICATION: {
    GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
    GET_UNREAD_COUNT: 'GET_UNREAD_COUNT',
  },
  VISIT: {
    GET_VISITS_OF_PATIENT: 'GET_VISITS_OF_PATIENT',
    GET_VISITS_BY_DAY_BY_ADMIN: 'GET_VISITS_BY_DAY_BY_ADMIN',
    STATIC_VISITS_BY_ADMIN: 'STATIC_VISITS_BY_ADMIN',
    GET_VISIT_DETAIL: 'GET_VISIT_DETAIL',
  },
  MEDICAL_RECORD: {
    GET_MEDICAL_RECORDS: 'GET_MEDICAL_RECORDS',
    GET_MEDICAL_RECORD_BY_ID: 'GET_MEDICAL_RECORD_BY_ID',
    GET_MEDICAL_RECORDS_BY_VISIT: 'GET_MEDICAL_RECORDS_BY_VISIT',
  },
  PRESCRIPTION: {
    GET_PRESCRIPTIONS: 'GET_PRESCRIPTIONS',
    GET_PRESCRIPTION_BY_ID: 'GET_PRESCRIPTION_BY_ID',
    GET_PRESCRIPTIONS_BY_VISIT: 'GET_PRESCRIPTIONS_BY_VISIT',
  },
  VISIT_SERVICE: {
    GET_VISIT_SERVICES_BY_VISIT: 'GET_VISIT_SERVICES_BY_VISIT',
  },
};

export default QUERY_KEY;
